#!/bin/bash
# send docker images over ssh to another docker daemon
# see also docker-pushmi-pullyu
set -euo pipefail

IMAGE=$1
REMOTE_HOST=$2

SIZE=$(docker images | rg "$IMAGE" | rev | cut  -d ' ' -f1 | rev)
PV_SIZE=$(echo "${SIZE%?}" | numfmt --from=iec)

docker save "$IMAGE" | pv --size "$PV_SIZE" | ssh -C "$REMOTE_HOST" docker load
