#!/bin/bash
# determines children of docker image for resolving dep issues
PARENT=$1
ALL=$(docker images -q)
for image in $ALL; do
    if [[ -n "$(docker history $image | grep $PARENT)" ]]; then
        echo $image
    fi
done
