#!/bin/bash
# send docker images over ssh to another docker daemon
# see also docker-pushmi-pullyu
set -euo pipefail

REMOTE_HOST=$1
IMAGE=$2

docker save "$IMAGE" | bzip2 | pv | ssh -C "$REMOTE_HOST" docker load
