#!/bin/bash
# send docker images over ssh to another docker daemon
# see also docker-pushmi-pullyu
set -euo pipefail

IMAGE=$1
REMOTE_HOST=$2

PV_SIZE=$(docker image inspect "$IMAGE" | jq ".[0].Size")

docker save "$IMAGE" | pv --size "$PV_SIZE" | ssh -C "$REMOTE_HOST" docker load
