#!/bin/bash
set -euo pipefail
IMAGES=()
while IFS="" read -r line; do IMAGES+=("$line"); done < <(docker images | rg ^\<none\> | awk '{print $3}')
if [ ${#IMAGES[@]} -eq 0 ]; then
  exit
fi
echo "${IMAGES[@]}"
docker rmi -f "${IMAGES[@]}"
