#!/bin/bash
set -exuo pipefail
IS_RUNNING=$(osascript -e 'application "Docker" is running')
if [ "$IS_RUNNING" = "true" ]; then
    if [ "${1:-}" != "-f" ]; then
        readarray -t CONTAINERS <<<"$(docker ps -q)"
        if [ ${#CONTAINERS[@]} -eq 0 ]; then
            echo "Stopping all containers..."
            docker stop "${CONTAINERS[@]}"
        fi
    fi
    echo "Quitting docker..."
    osascript -e 'quit app "Docker"'
    IS_RUNNING=$(osascript -e 'application "Docker" is running')
    if [ "$IS_RUNNING" = "true" ]; then
        echo "Docker is still running :("
        exit 1
    fi
fi
