#!/bin/bash
set -exuo pipefail
IS_RUNNING=$(osascript -e 'application "Docker" is running')
if [ "$IS_RUNNING" = "true" ]; then
    if [ "${1-}" != "-f" ]; then
        CONTAINERS=("$(docker ps -q)")
        if [ ${#CONTAINERS[@]} -eq 0 ]; then
            echo "Stopping all containers..."
            docker stop "${CONTAINERS[@]}"
        fi
    fi
    echo "Quitting docker..."
    osascript -e 'quit app "Docker"'
    TRIES=0
    while "$(osascript -e 'application "Docker" is running')" && TRIES -lt 10; do
        echo "Docker is still running :("
        sleep 1
        TRIES=$((TRIES + 1))
    done
    if "$(osascript -e 'application "Docker" is running')"; then
        pkill docker
    fi
fi
