#!/bin/bash
set -euo pipefail
docker-shutdown "$*"
if [ ! "$(osascript -e 'application "Docker" is running')" ]; then
    open --background -a Docker
    echo "Restarted Docker."
else
    echo "Docker still running."
fi
